### ISSUE TITLE
 ISP-7532FE (32FE) shows up, but fails to add to HA

### ISSUE THREAD

**Issue by kbalint** [8none1/idealLED#7] opened 2024-11-13 17:43 UTC
Hi, I've just bought this aforementioned ISP-7532FE (32FE) lights, and I can use it with Bluetooth on my phone. I've added your integration as well. For some time it just asked for a MAC address, after it identified the lights on it's own, but can not add it to HA (says unknown error occured) In the logs I see the following:

Logger: custom_components.ideal_led.idealled
Source: custom_components/ideal_led/idealled.py:362
integration: ideal_led ([documentation](https://github.com/8none1/idealLED/), [issues](https://github.com/8none1/idealLED/issues))
First occurred: 18:33:46 (1 occurrences)
Last logged: 18:33:46

Error getting status: ISP-7532FE - A6:0E:44:75:32:FE: Failed to connect after 9 attempt(s): No backend with an available connection slot that can reach address A6:0E:44:75:32:FE was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies (https://esphome.github.io/bluetooth-proxies/) near this device

The Raspberry PI running the HA and the Ligh dongle is ~ 3m in distance but on different levels in the house (there's a floor between). Can't really move any of them; but it keeps popping up when I restart HA. All together there are 17 other BT LE devices are in the house, and HA can pick up all of them without any problem here in a ~30m radius.

**Comment by 8none1** [comment] 2024-11-13 19:38
I don't think this is a problem with he integration itself.  The integration relies on HA to do all the actual low-level Bluetooth comms.  This error is coming from HA itself.

The number of simultaneous connections is limited by the hardware.  You can read more about that here: https://www.home-assistant.io/integrations/bluetooth/

However, BT LE devices are "connectionless" (kinda) so that shouldn't really be a problem. It's possible that your lights have a slightly different controller and there is a problem with the handshake, but I don't think it's that.

I'd suggest getting hold of a cheap ESP32 dev board and flashing it with ESPhome and setting up a Bluetooth proxy.  It's really easy and will probably solve your problem.

Also it's worth looking at the stand-along controller [here](https://github.com/8none1/idealLED/blob/main/idealled_controller.py)

You can run that on the Pi when HA is not running (you need to install [simplepyble](https://pypi.org/project/simplepyble/) too) and if that doesn't work either then it's likely that the controller is subtly different.

**Comment by ops244** [comment] 2024-11-16 07:59
hi, I have the same problem ...
at the same time, he connects the lamps (blinks several times), does not react to anything else...
------------------------------------------------------------------------------------------------------------------
Error getting status: IDL-F7EEFF - 36:C5:87:F7:EE:FF: Failed to connect after 11 attempt(s): No backend with an available connection slot that can reach address 36:C5:87:F7:EE:FF was found: The proxy/adapter is out of connection slots or the device is no longer reachable; Add additional proxies (https://esphome.github.io/bluetooth-proxies/) near this device

**Comment by 8none1** [comment] 2024-11-16 08:28
It's possible you both have newer hardware/firmware than I have on my devices and that they changed the protocol.  Perhaps you are running a newer version on HA than me. 

I'll upgrade to the latest version of HA and see if that makes any difference.  But right now I can't reproduce this problem.

**Comment by 8none1** [comment] 2024-11-16 17:21
I built a dev container off the bleeding edge of Home Assistant and I'm sorry to report that everything works fine here.  I was even passing the Bluetooth device on my laptop through to a docker container in order to control the lights. 

So I strongly suspect that this is because you have lights which have a later hardware/software revision than the version I have and that they changed the protocol.

Really the only option is to reverse engineering the new devices and decode the new protocol.

**Comment by ops244** [comment] 2024-11-17 01:57
Thank you, unfortunately I can't do that (

**Comment by 8none1** [comment] 2024-11-17 08:24
Can you share a link to where you bought your device. Maybe I can get one and take a look.

**Comment by ops244** [comment] 2024-11-17 08:37
this is a Christmas garland on the Christmas tree, it's unlikely that you have such a thing for sale, the era bran
-------------
erasg-03
-------------
![2024-11-17_11-36-52](https://github.com/user-attachments/assets/3489e8ed-b55e-42a4-acc8-b4ac6b4b1794)

**Comment by ops244** [comment] 2024-12-03 20:05
hello again, I found the same one on Aliexpress (but here it is 3 times more expensive than ours)
https://aliexpress.ru/item/1005007058367032.html?ysclid=m48vyej94z671206610&sku_id=12000039268852265

**Comment by 8none1** [comment] 2024-12-10 13:30
Next steps on this issue are for someone to grab a btsnoop log from an Android phone (as was done [here](https://github.com/8none1/idealLED/issues/10)) and we can attempt to reverse engineering the protocol remotely.

**Comment by dmitrkov** [comment] 2024-12-10 16:34
Hi. I'll try to grab a btsnoop log later when I have more free time

**Comment by dmitrkov** [comment] 2024-12-10 19:08
Here is the log I was able to extract after turning on/off 5 times 
[btsnoop_hci.log](https://github.com/user-attachments/files/18084642/btsnoop_hci.log)

**Comment by 8none1** [comment] 2024-12-11 09:25
The decrypted bytes are:

```text
Original string: 
Decrypted:       
Decimal:        
ASCII:          
Original string: 77 EF B2 D5 28 33 8F 3A 65 32 9A F3 85 68 3A BA
Decrypted:       05 4C 45 44 53 00 00 00 00 00 00 00 00 00 00 00
Decimal:        05 76 69 68 83 00 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDS
Original string: EA F7 F7 C6 77 CA 5F 9A 3B 7D 88 A8 7F C5 99 E2
Decrypted:       08 54 49 4D 45 02 15 01 07 00 00 00 00 00 00 00
Decimal:        08 84 73 77 69 02 21 01 07 00 00 00 00 00 00 00
ASCII:         TIME
Original string: E5 78 F4 5A 6A 4F 00 C2 6F 09 77 F8 F5 43 0C 87
Decrypted:       04 53 54 53 43 00 00 00 00 00 00 00 00 00 00 00
Decimal:        04 83 84 83 67 00 00 00 00 00 00 00 00 00 00 00
ASCII:          STSC
Original string: 50 05 3C 66 F0 82 35 97 2C AC 2E 20 1C 81 CC D2
Decrypted:       06 53 54 49 4E 00 00 00 00 00 00 00 00 00 00 00
Decimal:        06 83 84 73 78 00 00 00 00 00 00 00 00 00 00 00
ASCII:          STIN
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
Original string: CB B1 FD BF C5 60 D5 E4 53 C2 CB D9 28 B5 3F AB
Decrypted:       06 4C 45 44 4F 46 46 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 70 70 00 00 00 00 00 00 00 00 00
ASCII:          LEDOFF
Original string: 8E BC 70 EB 0D E6 99 D5 EB 16 38 3E 02 6D 2A C6
Decrypted:       06 4C 45 44 4F 4E 00 00 00 00 00 00 00 00 00 00
Decimal:        06 76 69 68 79 78 00 00 00 00 00 00 00 00 00 00
ASCII:          LEDON
```

Which means this is likely to be the same protocol as: https://github.com/8none1/idealLED/issues/10

Please could you also capture the following actions in one single file:

 - all red
 - all green
 - all blue
 - effect 1
 - effect 2
 - effect 3


It would be useful if you could perform each action 3 times, so for example in the app:  press red, red, red, green, green, green, blue blue blue.

This should give me enough information to add at least basic support for these lights until I find a cheap supplier with the same controller on Aliexpress.

**Comment by 8none1** [comment] 2024-12-11 10:40
I found this which I hope uses the new protocol:  https://s.click.aliexpress.com/e/_DmRYUR7

I'm going to order it.

**Comment by dmitrkov** [comment] 2024-12-11 16:04
[btsnoop_hci.log](https://github.com/user-attachments/files/18098803/btsnoop_hci.log)

- 3 times red
- 3 times green
- 3 times blue
- 3 times each effect from 1 to 11

**Comment by 8none1** [comment] 2024-12-11 18:25
Thanks @dmitrkov, this is very helpful.

So once decrypted here is what I can see.

## RGB

```text
Decrypted:       07 43 4F 4C 4F 00 FF 00 00 00 00 00 00 00 00 00
Decrypted:       07 43 4F 4C 4F 00 FF 00 00 00 00 00 00 00 00 00
Decrypted:       07 43 4F 4C 4F 00 FF 00 00 00 00 00 00 00 00 00
Decrypted:       07 43 4F 4C 4F FF 00 00 00 00 00 00 00 00 00 00
Decrypted:       07 43 4F 4C 4F FF 00 00 00 00 00 00 00 00 00 00
Decrypted:       07 43 4F 4C 4F FF 00 00 00 00 00 00 00 00 00 00
Decrypted:       07 43 4F 4C 4F 00 00 FF 00 00 00 00 00 00 00 00
Decrypted:       07 43 4F 4C 4F 00 00 FF 00 00 00 00 00 00 00 00
Decrypted:       07 43 4F 4C 4F 00 00 FF 00 00 00 00 00 00 00 00
```

It looks like the colours are ordered GRB and the byte string is pretty straight forward.

Working on the effects now, they are more confusing.

**Comment by 8none1** [comment] 2024-12-11 18:44
## Effects

Setting the effect seems to send four sets of bytes.
The first set is the same for each effect, this suggests that it is an instruction to switch to effects mode.
There are 34 of these in the capture which is close enough to 11 effects * 3 presses per effect.

```text
06 4C 49 47 48 54 0C 00 00 00 00 00 00 00 00 00
```
The second set of bytes is different for each effect, and so encodes the effect number some how.  This is the first effect.

```text
0E 45 46 46 01 07 03 FF 00 00 FF 80 00 FF FF 00
0E 45 46 46 01 07 13 00 FF 00 00 FF FF 00 00 FF
0E 45 46 46 01 07 21 80 00 FF 00 00 00 00 00 00
```

This is the second effect:

```text
0E 45 46 46 02 07 03 FF 00 00 FF 80 00 FF FF 00
0E 45 46 46 02 07 13 00 FF 00 00 FF FF 00 00 FF
0E 45 46 46 02 07 21 80 00 FF 00 00 00 00 00 00
```

From this we can deduce byte index 04 is the effect number.

I expect that the other bytes are colour patterns for the effect, speed, etc.

We can work those out later on, but now I think we have enough information to add basic support for this protocol. 

The next question is how to differentiate these lights from the older ones.  The previous version did not send any notifications, and so we have little to be able to "read" from these lights to tell.  Perhaps there is something in the manufacturer data that will help us. 

I will start a new branch to add support and debugging for these lights and let's see how far we get.  

Thanks for the help so far, I'll keep this issue update with progress.

**Comment by dmitrkov** [comment] 2024-12-11 18:52
Thank you! I'll look forward to hearing about it :)

**Comment by 8none1** [comment] 2024-12-11 19:59
There is a new, untested branch available here:  https://github.com/8none1/idealLED/tree/new_device_support

CAVEAT:  I cannot test this as I don't have the correct devices.  It may brick your device.  You should not use it. etc.

If you do want to test it you will have to:
 - Remove existing devices from the integration 
- Uninstall the existing integration
 - Clone this repo
 - switch to the new_device_support branch
 - copy the `custom_components/ideal_led` directory in to your HA `custom_components` directory such that `ideal_led` is inside `custom_components`
 - Restart HA

These are vague on purpose, only people really committed to trying this should proceed.

Hopefully it will restart and you will see your lights available to add.  You should be able to turn the lights on and off, change the colour and set effects.

It would be really nice if you could also enable debugging for this integration, remove the device again, and then readd it.  Turn off debugging and attach the logs to this issue.

**Comment by dmitrkov** [comment] 2024-12-11 20:26
With these changes will only the new device work or will support for the old ones (I have other devices that now work correctly) also remain?

**Comment by 8none1** [comment] 2024-12-11 20:29
This branch will only support the newer devices with the different protocol.  Once I get the debugging logs I hope to be able to tell which model a device is and then I can work on supporting both.

In the meantime, when you're done testing you can delete the devices and the folder from custom_components and reinstall via HACS, or checkout the `main` branch and copy the files over the top in `custom_components`.

**Comment by dmitrkov** [comment] 2024-12-12 07:23
Then I'll think about deploying a separate HA instance and testing this version on it. I'll post when I get the results.

**Comment by 8none1** [comment] 2024-12-12 09:08
That's a good plan.  If you use VS Code, check out dev containers:  https://community.home-assistant.io/t/developing-home-assistant-core-in-a-vscode-devcontainer/235650?page=2

Note there is some funny business around Bluetooth, but there is a comment on that post on how to get it to work.

Once you get it set up it is easier than running an entirely new instance of HA, but... getting it set up is hard.

**Comment by dmitrkov** [comment] 2024-12-12 17:37
I have deployed a separate instance of HA in virtualbox. Bluetooth works fine too (just route a USB device from the host to the guest OS).Then I did everything as you described, but this version doesn't see the new device(IDL-F86416). At the same time, it sees normal devices that work on the old version just fine
![image](https://github.com/user-attachments/assets/4b75de6b-c8c9-4b7d-8140-a571c08ed1bc)

The Bluetooth scanner on my phone detects this device and can connect to it
![image](https://github.com/user-attachments/assets/43a56d21-30f2-400f-91eb-15bfa8c215a5)

**Comment by dmitrkov** [comment] 2024-12-12 17:46
I replaced isp with idl in those places and now it works
![image](https://github.com/user-attachments/assets/6b02f659-42a5-4429-8ef1-0c49f1414723)
![image](https://github.com/user-attachments/assets/b6d96ded-b20b-4466-aea3-302aae65edea)

**Comment by dmitrkov** [comment] 2024-12-12 17:49
On/off, color and brightness change works. But the effect selection does not work

**Comment by 8none1** [comment] 2024-12-12 18:00
Ohhhhh.  This device reports it's name as `IDL`.  Looks like the new protocol has devices with names IDL and ISP.  Fun!

Yeah, you're fix for the name is correct, and I've incorporated it in to the code in a change I will push shortly.

This has shown something else which I was not expecting, and I can't explain how it's working AT ALL right now...

The UUIDs of the write service is TOTALLY different.  I don't understand how it's working.

On the original devices we are looking at UUIDs like `d44bc439-abfd-45a2-b575-925416129600`

In your bluetooth scanner could you expand the details and see if we can find out which is the WRITE service and what the others are?

**Comment by dmitrkov** [comment] 2024-12-12 18:03
[home-assistant.log](https://github.com/user-attachments/files/18115700/home-assistant.log)
![image](https://github.com/user-attachments/assets/89f7b4f1-e706-4cec-a3d2-21101d019549)

**Comment by 8none1** [comment] 2024-12-12 18:23
@dmitrkov can you try again with a fresh pull from the repo?

**Comment by dmitrkov** [comment] 2024-12-12 18:53
Yeah! It's all working now! On/Off, color change, brightness and effects. Except that effects can be 11, but the list can only select 10 (but that's a small thing).
Integration list now includes both `ISP` and `IDL`
![image](https://github.com/user-attachments/assets/48ca64c8-9de1-44d1-9716-47f030e3993a)

**Comment by 8none1** [comment] 2024-12-12 18:59
Awesome!!

One last request.  Could you:
 - Enable debugging
 - Remove the IDL device
 - Then re-add the IDL device
 - Disable debugging
 - Attach the log

This will hopefully enable it to grab the `manu_data` which I hope will differentiate between device versions.  

With that I can enable support for both and merge the branch in to main.

**Comment by dmitrkov** [comment] 2024-12-12 19:07
[home-assistant_ideal_led_2024-12-12T19-07-00.117Z.log](https://github.com/user-attachments/files/18116376/home-assistant_ideal_led_2024-12-12T19-07-00.117Z.log)

**Comment by dmitrkov** [comment] 2024-12-12 19:32
There is one more request. Is it possible to make effect selection available in automations? Now I decided to change the effect in automations using the scene, but it is inconvenient.

**Comment by 8none1** [comment] 2024-12-12 20:13
> There is one more request. Is it possible to make effect selection available in automations? Now I decided to change the effect in automations using the scene, but it is inconvenient.

You should already be able to do this:

![image](https://github.com/user-attachments/assets/509da244-1d98-40f3-bb5b-91b594ddbc5e)


You add the name of the effect to the effect input box.  Note `Effect 01` (not `Effect 1`)

**Comment by 8none1** [comment] 2024-12-12 20:21
Manufacturer data from new (top) and old (bottom) device:
```text
Manufacturer Data (hex): ['0x00', '0x61', '0x0e', '0x00', '0x00', '0x00', '0x00', '0x06']
Manufacturer Data (hex): ['0x00', '0x61', '0x10', '0x00', '0x06', '0x00', '0x02', '0x03', '0x00', '0x64', '0x00', '0x64']
```

We should be able to use this.

**Comment by dmitrkov** [comment] 2024-12-13 06:45
Oops. I didn't see any effect switching in the list but only on/off and figured there was no such option. Thanks!

**Comment by 8none1** [comment] 2024-12-24 15:43
Hi @dmitrkov , I just pushed some new code to the `new_device_support` branch which adds firmware version detection.

Would you mind pulling from the branch and removing and re-adding one of your newer devices and then telling me what the firmware version is being reported as?

You can find that information from this screen:

![image](https://github.com/user-attachments/assets/e0de1bed-f27d-4dbe-b141-f21041799511)

**Comment by dmitrkov** [comment] 2024-12-27 13:31
Hi @8none1. Today I received [a new device](https://www.aliexpress.com/item/1005008057244013.html) and tested its connection with the new version from the `new_device_support` branch. Yes, the firmware version is now displayed as well. `TR2407R004-01`
![image](https://github.com/user-attachments/assets/2bbcdc22-a3b5-4c4c-ab6a-f7947e6a76bd)

Firmware version of the device tested earlier `TR2110R002-15`
![image](https://github.com/user-attachments/assets/71b3426b-413c-4864-ad9a-a99f75eada8c)

**Comment by dmitrkov** [comment] 2024-12-27 13:42
I've noticed another strange behavior. After rebooting HA, these devices (both IDL-*) are turned on after starting the iDeal Led service

**Comment by 8none1** [comment] 2024-12-28 17:49
I pushed some changes to the "new_device_support" branch which might support both the old and new models at the same time.  If it doesn't work, it might be a case of changing the `COMMAND_LOOKUP` table in `const.py` to match the firmware version with the correct command set.

**Comment by 8none1** [comment] 2024-12-28 18:05
... I think I made a mistake on how to identify which firmware a device is using.  I have a fix on the way.

Are your two devices [shown above](https://github.com/8none1/idealLED/issues/7#issuecomment-2563705658) both working with the "new" codes?

**Comment by dmitrkov** [comment] 2024-12-29 08:11
I haven't checked out the new version yet.

**Comment by 8none1** [comment] 2024-12-30 15:44
I've tested the new branch on all my iDeal devices and it seems to work.  So I have merged the development branch in to main.  Please feel free to comment here and re-open this bug if things still don't work.

**Closed by 8none1** 2024-12-30 15:44 UTC

**Comment by ops244** [comment] 2024-12-30 18:35
[Uploading home-assistant_2024-12-30T18-32-13.497Z.log…]()

**Comment by ops244** [comment] 2024-12-30 18:35
[home-assistant_2024-12-30T18-32-13.497Z.log](https://github.com/user-attachments/files/18277048/home-assistant_2024-12-30T18-32-13.497Z.log)

**Comment by 8none1** [comment] 2024-12-30 18:38
@ops244 please open a new issue (also:  delete your devices and re-add them and it should fix it)
